export const SAMPLE_PLAYERS = [
  {
    id: 1,
    name: "โอ๊ต",
    skill_level: "intermediate",
    stamina: 80,
    playing_style: "attacker",
    image: "https://via.placeholder.com/150?text=Player+1",
  },
  {
    id: 2,
    name: "หนุ่ย",
    skill_level: "intermediate",
    stamina: 75,
    playing_style: "defender",
    image: "https://via.placeholder.com/150?text=Player+2",
  },
  {
    id: 3,
    name: "ปู",
    skill_level: "advanced",
    stamina: 90,
    playing_style: "balanced",
    image: "https://via.placeholder.com/150?text=Player+3",
  },
  {
    id: 4,
    name: "ไปร์",
    skill_level: "beginner",
    stamina: 65,
    playing_style: "attacker",
    image: "https://via.placeholder.com/150?text=Player+4",
  },
];
const samplePlayers = [
  {
    id: 1,
    name: "สมชาย ใจดี",
    skill_level: "intermediate",
    stamina: 80,
    playing_style: "attacker",
    image: "https://via.placeholder.com/150?text=Player+1",
  },
  {
    id: 2,
    name: "สมหญิง สุขใจ",
    skill_level: "intermediate",
    stamina: 75,
    playing_style: "defender",
    image: "https://via.placeholder.com/150?text=Player+2",
  },
  {
    id: 3,
    name: "อนันต์ ชนะชัย",
    skill_level: "advanced",
    stamina: 90,
    playing_style: "balanced",
    image: "https://via.placeholder.com/150?text=Player+3",
  },
  {
    id: 4,
    name: "ดารา สดใส",
    skill_level: "beginner",
    stamina: 65,
    playing_style: "attacker",
    image: "https://via.placeholder.com/150?text=Player+4",
  },
];
